

# This file was *autogenerated* from the file debug/compare_2iso.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_69 = Integer(69); _sage_const_22 = Integer(22); _sage_const_70 = Integer(70); _sage_const_49 = Integer(49); _sage_const_25 = Integer(25); _sage_const_21 = Integer(21); _sage_const_56 = Integer(56); _sage_const_28 = Integer(28)
eA = _sage_const_3 
eB = _sage_const_2 
p = _sage_const_2 **eA * _sage_const_3 **eB - _sage_const_1 
Fp = GF(p)
R = PolynomialRing(Fp, names=('x',)); (x,) = R._first_ngens(1)
Fp2 = GF(p**_sage_const_2 , modulus=x**_sage_const_2  + _sage_const_1 , names=('i',)); (i,) = Fp2._first_ngens(1)

def xDBL(A, X, Z):
    A24 = (A + _sage_const_2 ) / _sage_const_4 
    add = X + Z
    sub = X - Z
    sq_add = add * add
    sq_sub = sub * sub
    four_XZ = sq_add - sq_sub
    next_X = sq_add * sq_sub
    next_Z = four_XZ * (sq_sub + A24 * four_XZ)
    return next_X, next_Z

def get_next_A_new(XK, ZK):
    XK2 = XK * XK
    ZK2 = ZK * ZK
    return (_sage_const_2  * ZK2 - _sage_const_4  * XK2) / ZK2

def eval_new(XK, ZK, X, Z):
    t0 = (XK + ZK) * (X - Z)
    t1 = (XK - ZK) * (X + Z)
    return X * (t0 + t1), Z * (t0 - t1)

def on_curve(A, X, Z):
    if Z == _sage_const_0 :
        return True, "inf"
    xv = X / Z
    E = EllipticCurve(Fp2, [_sage_const_0 , A, _sage_const_0 , _sage_const_1 , _sage_const_0 ])
    try:
        P = E.lift_x(xv)
        return True, P.order()
    except Exception:
        return False, None

A = Fp2(_sage_const_6 )
E0 = EllipticCurve(Fp2, [_sage_const_0 , A, _sage_const_0 , _sage_const_1 , _sage_const_0 ])
P = E0(Fp2(_sage_const_69  + _sage_const_22 *i), Fp2(_sage_const_70  + _sage_const_49 *i))
Q = E0(Fp2(_sage_const_25  + _sage_const_21 *i), Fp2(_sage_const_56  + _sage_const_28 *i))
Spt = P + Q
S = (Spt.x(), Fp2(_sage_const_1 ))

print("=== corrected chain ===")
for i in [_sage_const_2 , _sage_const_1 , _sage_const_0 ]:
    K = S
    for j in range(i):
        K = xDBL(A, K[_sage_const_0 ], K[_sage_const_1 ])
    ok, ordK = on_curve(A, K[_sage_const_0 ], K[_sage_const_1 ])
    K2 = xDBL(A, K[_sage_const_0 ], K[_sage_const_1 ])
    kx = K[_sage_const_0 ]/K[_sage_const_1 ] if K[_sage_const_1 ] != _sage_const_0  else "inf"
    print("i=%s K on curve %s ord %s 2K inf %s Kx %s" % (i, ok, ordK, K2[_sage_const_1 ]==_sage_const_0 , kx))
    A = get_next_A_new(K[_sage_const_0 ], K[_sage_const_1 ])
    S = eval_new(K[_sage_const_0 ], K[_sage_const_1 ], S[_sage_const_0 ], S[_sage_const_1 ])
    okS, ordS = on_curve(A, S[_sage_const_0 ], S[_sage_const_1 ])
    sx = S[_sage_const_0 ]/S[_sage_const_1 ] if S[_sage_const_1 ] != _sage_const_0  else "inf"
    print("  A'=%s S on curve %s ord %s Sx %s" % (A, okS, ordS, sx))

