

# This file was *autogenerated* from the file debug/generate_params.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_6 = Integer(6); _sage_const_0 = Integer(0)# ==============================================================================
# SIDH Toy Parameter Generator (p = 71) - Stable & Correct Version
# ==============================================================================

eA = _sage_const_3 
eB = _sage_const_2 
f = _sage_const_1 
p = f * (_sage_const_2 **eA) * (_sage_const_3 **eB) - _sage_const_1  # 1 * 8 * 9 - 1 = 71

print(f"/* ===== Generating Parameters for p = {p} ===== */")

# 拡大体 F_{p^2} の定義
Fp = GF(p)
R = PolynomialRing(Fp, 'x')
x = R.gen()
Fp2 = GF(p**_sage_const_2 , name='i', modulus=x**_sage_const_2  + _sage_const_1 )
i = Fp2.gen()

# 初期モンゴメリ曲線 E_0: y^2 = x^3 + 6x^2 + x
A0 = Fp2(_sage_const_6 )
E0 = EllipticCurve(Fp2, [_sage_const_0 , A0, _sage_const_0 , _sage_const_1 , _sage_const_0 ])

# 超特異楕円曲線の各生成元の最大位数は p+1
max_order = p + _sage_const_1 

# 群の生成元を2つ取得
G = E0.abelian_group()
gens = G.gens()
G1 = gens[_sage_const_0 ].element()
G2 = gens[_sage_const_1 ].element()

# Alice の基底点 (位数 2^eA)
cofactor_A = max_order // (_sage_const_2 **eA) # 72 // 8 = 9
PA = cofactor_A * G1
QA = cofactor_A * G2
RA = PA - QA

# Bob の基底点 (位数 3^eB)
cofactor_B = max_order // (_sage_const_3 **eB) # 72 // 9 = 8
PB = cofactor_B * G1
QB = cofactor_B * G2
RB = PB - QB

# C++ 定数出力関数
def print_cpp_point(name, Pt):
    if Pt.is_zero():
        print(f"// ERROR: {name} is the Point at Infinity")
        return
    
    x_val = Pt.x()
    # Fp2要素から実部と虚部を安全に抽出
    coeffs = x_val.polynomial().list()
    real_part = coeffs[_sage_const_0 ] if len(coeffs) > _sage_const_0  else _sage_const_0 
    imag_part = coeffs[_sage_const_1 ] if len(coeffs) > _sage_const_1  else _sage_const_0 
    
    print(f"const ProjectivePoint {name}(Fp2({real_part}, {imag_part}), Fp2(1, 0));")

print("// ===== C++ Global Constants (Copy & Paste to your code) =====")
print(f"const uint64_t P_PRIME = {p};")
print(f"const int E_A = {eA};")
print(f"const int E_B = {eB};")
print(f"const Fp2 INITIAL_A(6, 0);\n")

print("// Alice's Basis Points (Order 2^eA)")
print_cpp_point("P_A", PA)
print_cpp_point("Q_A", QA)
print_cpp_point("R_A", RA)

print("\n// Bob's Basis Points (Order 3^eB)")
print_cpp_point("P_B", PB)
print_cpp_point("Q_B", QB)
print_cpp_point("R_B", RB)

