

# This file was *autogenerated* from the file debug/verify_e1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_6 = Integer(6); _sage_const_0 = Integer(0); _sage_const_69 = Integer(69); _sage_const_22 = Integer(22); _sage_const_70 = Integer(70); _sage_const_49 = Integer(49); _sage_const_25 = Integer(25); _sage_const_21 = Integer(21); _sage_const_56 = Integer(56); _sage_const_28 = Integer(28); _sage_const_48 = Integer(48); _sage_const_59 = Integer(59); _sage_const_63 = Integer(63); _sage_const_24 = Integer(24); _sage_const_4 = Integer(4); _sage_const_40 = Integer(40); _sage_const_45 = Integer(45); _sage_const_42 = Integer(42); _sage_const_12 = Integer(12); _sage_const_58 = Integer(58); _sage_const_68 = Integer(68); _sage_const_32 = Integer(32); _sage_const_39 = Integer(39); _sage_const_34 = Integer(34)# ==========================================
# verify_e1.sage
# ==========================================
eA = _sage_const_3 
eB = _sage_const_2 
p = _sage_const_1  * (_sage_const_2 **eA) * (_sage_const_3 **eB) - _sage_const_1 

Fp = GF(p)
R = PolynomialRing(Fp, 'x')
x = R.gen()
Fp2 = GF(p**_sage_const_2 , name='i', modulus=x**_sage_const_2  + _sage_const_1 )
i = Fp2.gen()

A0 = Fp2(_sage_const_6 )
E0 = EllipticCurve(Fp2, [_sage_const_0 , A0, _sage_const_0 , _sage_const_1 , _sage_const_0 ])

# generate_params と同じ方法で完全に同一の点を生成
#max_order = p + 1
#G = E0.abelian_group()
#gens = G.gens()
#G1 = gens[0].element()
#G2 = gens[1].element()

#cofactor_A = max_order // (2**eA)
#PA = cofactor_A * G1
#QA = cofactor_A * G2

#cofactor_B = max_order // (3**eB)
#PB = cofactor_B * G1
#QB = cofactor_B * G2
#RB = PB - QB
PA = E0(
    Fp2(_sage_const_69  + _sage_const_22 *i),
    Fp2(_sage_const_70  + _sage_const_49 *i)
)

QA = E0(
    Fp2(_sage_const_25  + _sage_const_21 *i),
    Fp2(_sage_const_56  + _sage_const_28 *i)
)

RA = E0(
    Fp2(_sage_const_48  + _sage_const_59 *i),
    Fp2(_sage_const_63  + _sage_const_24 *i)
)

PB = E0(
    Fp2(_sage_const_4  + _sage_const_40 *i),
    Fp2(_sage_const_45  + _sage_const_42 *i)
)

QB = E0(
    Fp2(_sage_const_12  + _sage_const_58 *i),
    Fp2(_sage_const_68  + _sage_const_32 *i)
)

RB = E0(
    Fp2(_sage_const_0  + _sage_const_39 *i),
    Fp2(_sage_const_34  + _sage_const_22 *i)
)

# ==========================================
# 1ステップの同種写像の検証 (e = 1)
# ==========================================

# 1. 秘密鍵 m_A = 1 の秘密点 S_A = PA + QA
SA = PA + QA

# 2. 2倍算を2回(4倍)して、位数 2 の核 K を抽出
K = _sage_const_4  * SA
SA = PA + QA
K = _sage_const_4  * SA

print("S_A =", SA.x())
print("K =", K.x())

print("=== SageMath Verification (e = 1) ===")
print(f"Kernel K (Affine x): {K.x()}")

# 3. K を核とする 2-同種写像を計算
phi = E0.isogeny(K)
E1 = phi.codomain()

print("\n[2] Next Curve Parameter (SageMath):")
print(f"A' (a2 parameter) : {E1.a2()}")

print("\n[3] Pushed-forward Points (Bob's Basis in SageMath):")
print(f"phi(P_B) (Affine x): {phi(PB).x()}")
print(f"phi(Q_B) (Affine x): {phi(QB).x()}")
print(f"phi(R_B) (Affine x): {phi(RB).x()}")

