

# This file was *autogenerated* from the file debug/verify_sike.sage
from sage.all_cmdline import *   # import sage library

_sage_const_71 = Integer(71); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_9 = Integer(9); _sage_const_4 = Integer(4)# ==========================================
# verify_sike.sage
# ==========================================
p = _sage_const_71 
Fp = GF(p)
R = PolynomialRing(Fp, 'x')
x = R.gen()
Fp2 = GF(p**_sage_const_2 , name='i', modulus=x**_sage_const_2  + _sage_const_1 )
i = Fp2.gen()

E0 = EllipticCurve(Fp2, [_sage_const_0 , _sage_const_6 , _sage_const_0 , _sage_const_1 , _sage_const_0 ])

# --- Generate Basis ---
max_order = p + _sage_const_1 
G = E0.abelian_group().gens()
G1, G2 = G[_sage_const_0 ].element(), G[_sage_const_1 ].element()

PA, QA = (max_order // _sage_const_8 ) * G1, (max_order // _sage_const_8 ) * G2
PB, QB = (max_order // _sage_const_9 ) * G1, (max_order // _sage_const_9 ) * G2
RB = PB - QB

# --- Kernel K ---
K = _sage_const_4  * (PA + QA)
xK = K.x()

print("=== SIKE Specification Verification ===")
print(f"Kernel K (Affine x) : {xK}")

# --- SIKE 2-Isogeny Formulas ---
XK2 = xK**_sage_const_2 
ZK2 = Fp2(_sage_const_1 )

C24 = (XK2 - ZK2)**_sage_const_2 
A24plus = _sage_const_2  * (XK2 + ZK2)**_sage_const_2 
next_A = (_sage_const_4  * A24plus - _sage_const_2  * C24) / C24

print(f"\n[2] Expected Next A'  : {next_A}")

def sike_eval(Q):
    XQ, ZQ = Q.x(), Fp2(_sage_const_1 )
    t0 = (XQ + ZQ) * (xK - Fp2(_sage_const_1 ))
    t1 = (XQ - ZQ) * (xK + Fp2(_sage_const_1 ))
    next_X = XQ * (t0 + t1)
    next_Z = ZQ * (t0 - t1)
    return next_X / next_Z

print("\n[3] Expected Pushed-forward Points (Affine x):")
print(f"phi(P_B) : {sike_eval(PB)}")
print(f"phi(Q_B) : {sike_eval(QB)}")
print(f"phi(R_B) : {sike_eval(RB)}")

