

# This file was *autogenerated* from the file debug/verify_e3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_71 = Integer(71); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_9 = Integer(9); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3)# ==========================================
# verify_e3.sage
# ==========================================
p = _sage_const_71 
Fp = GF(p)
R = PolynomialRing(Fp, 'x')
x = R.gen()
Fp2 = GF(p**_sage_const_2 , name='i', modulus=x**_sage_const_2  + _sage_const_1 )
i = Fp2.gen()

E0 = EllipticCurve(Fp2, [_sage_const_0 , _sage_const_6 , _sage_const_0 , _sage_const_1 , _sage_const_0 ])

# --- 基底点の生成 ---
max_order = p + _sage_const_1 
G = E0.abelian_group().gens()
G1, G2 = G[_sage_const_0 ].element(), G[_sage_const_1 ].element()
PA, QA = (max_order // _sage_const_8 ) * G1, (max_order // _sage_const_8 ) * G2
PB, QB = (max_order // _sage_const_9 ) * G1, (max_order // _sage_const_9 ) * G2
RB = PB - QB

# --- SIKE Montgomery Formulas in Python ---
def get_next_A(XK, ZK):
    C24 = (XK**_sage_const_2  - ZK**_sage_const_2 )**_sage_const_2 
    A24plus = _sage_const_2  * (XK**_sage_const_2  + ZK**_sage_const_2 )**_sage_const_2 
    return (_sage_const_4  * A24plus - _sage_const_2  * C24) / C24

def isogeny_eval(XQ, ZQ, XK, ZK):
    t0 = (XQ + ZQ) * (XK - ZK)
    t1 = (XQ - ZQ) * (XK + ZK)
    t2 = t0 + t1
    t3 = t0 - t1
    t2 = t2**_sage_const_2 
    t3 = t3**_sage_const_2 
    next_X = XQ * t2
    next_Z = ZQ * t3
    return next_X, next_Z

def xDBL(X, Z, A):
    t0 = (X + Z)**_sage_const_2 
    t1 = (X - Z)**_sage_const_2 
    C = t0 - t1
    next_X = t0 * t1
    A24 = (A + Fp2(_sage_const_2 )) / Fp2(_sage_const_4 )
    t0 = t0 + A24 * C
    next_Z = C * t0
    return next_X, next_Z

# --- ループの初期設定 ---
S = PA + QA
SX, SZ = S.x(), Fp2(_sage_const_1 )

PX, PZ = PB.x(), Fp2(_sage_const_1 )
QX, QZ = QB.x(), Fp2(_sage_const_1 )
RX, RZ = RB.x(), Fp2(_sage_const_1 )
A = Fp2(_sage_const_6 )

print("=== SIKE e=3 Chain Verification ===")
print(f"[1] Initial Secret Point S (Affine x): {SX}")

# --- e=3 の同種写像チェーンループ ---
for step in range(_sage_const_3 ):
    # 核 K の計算: 2^(2 - step) 倍
    KX, KZ = SX, SZ
    for _ in range(_sage_const_2  - step):
        KX, KZ = xDBL(KX, KZ, A)
    
    # 次の曲線を計算
    A_next = get_next_A(KX, KZ)
    
    # 点の移送
    if step < _sage_const_2 :
        SX, SZ = isogeny_eval(SX, SZ, KX, KZ)
    PX, PZ = isogeny_eval(PX, PZ, KX, KZ)
    QX, QZ = isogeny_eval(QX, QZ, KX, KZ)
    RX, RZ = isogeny_eval(RX, RZ, KX, KZ)
    
    # 曲線パラメータの更新
    A = A_next

# --- アフィン座標に戻して出力 ---
print(f"\n[2] Expected Next Curve Parameter A': {A}")
print("\n[3] Expected Pushed-forward Points (Affine x):")
print(f"phi(P_B) : {PX / PZ}")
print(f"phi(Q_B) : {QX / QZ}")
print(f"phi(R_B) : {RX / RZ}")

