

# This file was *autogenerated* from the file debug/verify_2_e1_af.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_6 = Integer(6); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4)# ==========================================
# verify_e1_affine.sage
# ==========================================
eA = _sage_const_3 
eB = _sage_const_2 
p = _sage_const_1  * (_sage_const_2 **eA) * (_sage_const_3 **eB) - _sage_const_1 

Fp = GF(p)
R = PolynomialRing(Fp, 'x')
x = R.gen()
Fp2 = GF(p**_sage_const_2 , name='i', modulus=x**_sage_const_2  + _sage_const_1 )
i = Fp2.gen()

A0 = Fp2(_sage_const_6 )
E0 = EllipticCurve(Fp2, [_sage_const_0 , A0, _sage_const_0 , _sage_const_1 , _sage_const_0 ])

# generate_params と同じ方法で完全に同一の点を生成
max_order = p + _sage_const_1 
G = E0.abelian_group()
gens = G.gens()
G1 = gens[_sage_const_0 ].element()
G2 = gens[_sage_const_1 ].element()

cofactor_A = max_order // (_sage_const_2 **eA)
PA = cofactor_A * G1
QA = cofactor_A * G2

cofactor_B = max_order // (_sage_const_3 **eB)
PB = cofactor_B * G1
QB = cofactor_B * G2
RB = PB - QB

# ==========================================
# 1ステップの同種写像の検証 (e = 1) - アフィン完全版
# ==========================================

# 1. 秘密鍵 m_A = 1 の秘密点 S_A = PA + QA
SA = PA + QA

# 2. 2倍算を2回(4倍)して、位数 2 の核 K を抽出
K = _sage_const_4  * SA

print("=== SageMath Verification (e = 1) [Affine Coordinates] ===")

# アフィン座標表示用ヘルパー関数
def format_affine_point(Pt):
    if Pt.is_zero():
        return "Point at Infinity"
    
    x_val = Pt.x()
    x_coeffs = x_val.polynomial().list()
    xr = x_coeffs[_sage_const_0 ] if len(x_coeffs) > _sage_const_0  else _sage_const_0 
    xi = x_coeffs[_sage_const_1 ] if len(x_coeffs) > _sage_const_1  else _sage_const_0 

    y_val = Pt.y()
    y_coeffs = y_val.polynomial().list()
    yr = y_coeffs[_sage_const_0 ] if len(y_coeffs) > _sage_const_0  else _sage_const_0 
    yi = y_coeffs[_sage_const_1 ] if len(y_coeffs) > _sage_const_1  else _sage_const_0 

    return f"AffinePoint(Fp2({xr}, {xi}), Fp2({yr}, {yi}))"

print(f"Kernel K : {format_affine_point(K)}")

# 3. K を核とする 2-同種写像を計算
phi = E0.isogeny(K)
E1 = phi.codomain()

print("\n[2] Next Curve Parameter (SageMath):")
print(f"A' (a2 parameter) : {E1.a2()}")

print("\n[3] Pushed-forward Points (Bob's Basis in SageMath):")
print(f"phi(P_B) : {format_affine_point(phi(PB))}")
print(f"phi(Q_B) : {format_affine_point(phi(QB))}")
print(f"phi(R_B) : {format_affine_point(phi(RB))}")

